### ISSUE TITLE
这个仓库只能给root用户使用

### ISSUE THREAD

**Issue by bugsz** [cxz66666/OS-Dockerfile#1]
1. antigen里面的缓存文件都是丢到root文件夹下的，这导致其它用户无法使用。
2. dockerfile里面配置也是为root设置的，建议加上一个变量让大家自行选择。
3. 文件是crlf的，放到实验提供镜像里面会出错，建议改成lf。

**Comment by cxz66666** [comment]
1. antigen已经使用镜像源，删除缓存包
2. dockerfile已经支持其他用户
